### PR TITLE
Rename `:primitive` as `:module`.

### PR DESCRIPTION
**Pull request by jemc**
As [discussed in Zulip](https://savi.zulipchat.com/#narrow/stream/294905-language/topic/.3Aprimitive.20rename.20to.20.3Amodule), we think this will make the intent of the concept more clear to newcomers that don't already know Pony concepts.

### CODE REVIEW

**Review by mneumann — APPROVED** [review]
Looks good!

Very clear when used as a "bag of functions". I assume you'll add mixin capabilities later on :).

Only slightly confusing (until I get used to it) in case the module is used as a "singleton" value, e.g. `None`. In Rust, this would be just a zero-sized `struct`. For that purpose, `primitive` wasn't a very bad choice IMHO.

I am curious how a Savi `:class` with no fields will be different from a `:module`. Is it merely that `:module` restricts all functions to be `non` and that no constructors are allowed (or are the constructors statically initialized)?

**Review by tonchis — APPROVED** [review]

**Comment by jemc** [comment]
> I am curious how a Savi `:class` with no fields will be different from a `:module`. Is it merely that `:module` restricts all functions to be `non` and that no constructors are allowed (or are the constructors statically initialized)?

Yes, a `:module` cannot be constructed and it has one statically allocated singleton instance, so when you check its identity you will always see the same identity.

An empty `:class` would have a different identity each time, so you could for example use one as you use `make_ref` in Erlang to get a token that is guaranteed to be unique during its lifetime. In this case the token is the pointer address where the class was allocated, which is guaranteed to be unique by the garbage collector.

**Comment by jemc** [comment]
> Very clear when used as a "bag of functions". I assume you'll add mixin capabilities later on :).

We do have `:is` and `:copies` today which are two slightly different ways of mixing in common methods, though I've been using them with `:trait` as the mixin source rather than `:primitive`/`:module`.

`:is` implies that there is a direct subtype relationship, so it would only work with `:trait` (nothing can be a subtype of a concrete type, including a `:primitive`/`:module`. An example is the `Equatable` trait - when you "mix it in" via `:is` the compiler will also enforce that you do everything necessary to make it a valid subtype of the trait.

`:copies` by contrast will only mix in the functions but will not enforce that the end result is a valid subtype. So this can be used for code sharing without enforcing a subtyping relationship.

In both cases I think `:trait` is usually the most logical choice for a "mix in" source, but in theory I think you could use a `:primitive`/`:module` as the mix in source for a `:copies` declaration. You just wouldn't have the ability to have non-implemented methods in the source module like you do with trait.

In general, I think when you see "module" in Savi, you should think about modules from functional programming languages rather than modules from Ruby. In Ruby, the concept of a module is rather conflated together with what in Savi we would call a `:trait`. But if you have to think about Ruby, then think about `module_function` which is basically the right concept for a Savi module.

**Comment by jemc** [comment]
> e.g. `None`. In Rust, this would be just a zero-sized `struct`

In theory we could make it a zero-sized `struct` in Savi too, though in today's Savi compiler that would be non-optimal because when we wrap it in a union (e.g. `(String | None)`) we would allocate a new wrapper every time. We don't (yet, I suppose) have an optimization in place that recognizes that an empty struct could use a statically allocated wrapper - quite similar to `:primitive`/`:module`.

**Pull request merged**
